/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "后端云",
  "tagline": "Dinosaurs are cool",
  "favicon": "https://avatars.githubusercontent.com/u/15382060?v=4",
  "url": "https://www.backendcloud.cn",
  "baseUrl": "/",
  "organizationName": "backendcloud",
  "projectName": "后端云",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "zh-Hans",
    "locales": [
      "zh-Hans"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "C:\\Users\\hanwei\\Documents\\Github\\backendcloud.github.io\\sidebars.js",
          "editUrl": "https://github.com/backendcloud/backendcloud.github.io/tree/main/"
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/backendcloud/backendcloud.github.io/tree/main/",
          "blogSidebarTitle": "全部博文",
          "blogSidebarCount": "ALL"
        },
        "theme": {
          "customCss": "C:\\Users\\hanwei\\Documents\\Github\\backendcloud.github.io\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "navbar": {
      "title": "后端云",
      "logo": {
        "alt": "My Site Logo",
        "src": "https://avatars.githubusercontent.com/u/15382060?v=4"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "知识库"
        },
        {
          "to": "/blog",
          "label": "博客",
          "position": "left"
        },
        {
          "href": "https://github.com/backendcloud/backendcloud.github.io",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "站内导航：",
          "items": [
            {
              "label": "知识库",
              "to": "/docs/intro"
            },
            {
              "label": "博客",
              "to": "/blog"
            }
          ]
        },
        {
          "title": "更多站外资源：",
          "items": [
            {
              "label": "存档的hexo博客（2023年04月17日之前的博客文章）",
              "href": "https://www.backendcloud.cn/2023/04/17/Hexo2Docusaurus/"
            },
            {
              "label": "GitHub（后端云网址里的所有示例代码的相关仓库）",
              "href": "https://github.com/backendcloud"
            },
            {
              "label": "GitHub（后端云网站的代码仓库）",
              "href": "https://github.com/backendcloud/backendcloud.github.io"
            },
            {
              "label": "GitHub（KubeFusion项目仓库）",
              "href": "https://github.com/kubefusion"
            },
            {
              "label": "GitHub（通用人工智能和自动化相结合的项目仓库）",
              "href": "https://github.com/AutoGeneralAI"
            },
            {
              "label": "GitHub（其他代码仓库）",
              "href": "https://github.com/c-hanwei"
            }
          ]
        }
      ],
      "copyright": "苏ICP备15031601-2号 Copyright © 2023 后端云"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
